name: Deploy to GitHub Pages (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Single-page app fallback for GitHub Pages
      - name: SPA 404 fallback
        run: cp dist/index.html dist/404.html

      # Avoid Jekyll processing on GH Pages
      - name: Disable Jekyll
        run: touch dist/.nojekyll

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
